/** Production schema. Postgres is the target; SQLite is local-only (translated). */
export { sqliteSchema, postgresSchema, applyMigrations, SCHEMA_VERSION } from "./migrations.ts";

export const TABLES = [
  "indexer_state",
  "tokens",
  "markets",
  "quote_assets",
  "pool_relationships",
  "trades",
  "candles",
  "bonding_states",
  "graduations",
  "reward_events",
  "claims",
  "selfburn",
  "flywheel",
  "core_buybacks",
  "top10_epochs",
  "targets",
  "keeper_operations",
  "guardian_events",
  "route_venues",
  "external_price_marks",
  "metadata",
  "leader_locks",
  "alerts",
  "tickers",
  "launch_auths",
] as const;
