#!/usr/bin/env npx tsx
/**
 * Generate versioning + deployment docs from config, and fail CI on drift.
 *
 * Source of truth for protocol semver: docs/version.json
 * Factory version: contracts/src/ReactorFactory.sol FACTORY_VERSION (immutable)
 * Economics: contracts/src/ReactorConstants.sol (never change from this script)
 */
import assert from "node:assert/strict";
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

export type ProtocolVersion = {
  protocolVersion: string;
  factoryVersion: number;
  factoryVersionLabel: string;
  releaseTag: string;
  releaseDate: string;
  status: string;
  notes: string;
};

type RegistryContract = {
  name: string;
  addressKey: string | null;
  factoryVersion: number | null;
};

type RegistryNetwork = {
  id: string;
  label: string;
  placeholder: boolean;
  claimed: boolean;
  chain: string;
  chainId: number;
  explorer: string | null;
  addressFile: string | null;
  sourceCommit: string | null;
  sourceTag: string | null;
  deploymentDate: string | null;
  verificationUrl: string | null;
  verificationNote: string;
  note: string;
};

type Registry = {
  schema: number;
  networks: RegistryNetwork[];
  contracts: RegistryContract[];
};

const GENERATED_BANNER =
  "<!-- GENERATED by scripts/sync-docs.ts from docs/version.json + deployments/registry.json. Do not edit by hand. -->";

function read(rel: string): string {
  return readFileSync(join(root, rel), "utf8");
}

function readJson<T>(rel: string): T {
  return JSON.parse(read(rel)) as T;
}

export function loadVersion(): ProtocolVersion {
  return readJson<ProtocolVersion>("docs/version.json");
}

function solAssign(src: string, name: string): string {
  const m = src.match(new RegExp(`\\b${name}\\s*=\\s*([^;]+);`));
  if (!m) throw new Error(`missing Solidity assignment ${name}`);
  return m[1]!.trim();
}

function solUint(src: string, name: string): number {
  const raw = solAssign(src, name).replace(/_/g, "");
  const hours = /^(\d+)\s*hours$/.exec(raw);
  if (hours) return Number(hours[1]) * 3600;
  const days = /^(\d+)\s*days$/.exec(raw);
  if (days) return Number(days[1]) * 86400;
  const ether = /^(\d+)\s*ether$/.exec(raw);
  if (ether) return Number(ether[1]);
  const n = Number(raw);
  if (!Number.isFinite(n)) throw new Error(`cannot parse ${name}=${raw}`);
  return n;
}

function bpsToPct(bps: number): string {
  const pct = bps / 100;
  return Number.isInteger(pct) ? `${pct}%` : `${pct}%`;
}

export function loadCodeConstants() {
  const constants = read("contracts/src/ReactorConstants.sol");
  const factory = read("contracts/src/ReactorFactory.sol");
  const ticker = read("contracts/src/libraries/Ticker.sol");
  const tickerTs = read("packages/reactor/src/ticker.ts");
  const factoryVersion = solUint(factory, "FACTORY_VERSION");
  const lockSol = solUint(ticker, "LOCK_SECONDS");
  const lockTs = Number((/TICKER_LOCK_SECONDS\s*=\s*([^;]+);/.exec(tickerTs) ?? [])[1]?.replace(/\s/g, "").split("*").reduce((a, b) => a * Number(b), 1));
  return {
    protocolFeeBps: solUint(constants, "PROTOCOL_FEE_BPS"),
    holderFeeBps: solUint(constants, "HOLDER_FEE_BPS"),
    flywheelFeeBps: solUint(constants, "FLYWHEEL_FEE_BPS"),
    coreFeeBps: solUint(constants, "CORE_FEE_BPS"),
    defaultSupplyBillions: solUint(constants, "DEFAULT_SUPPLY") / 1_000_000_000,
    defaultSupplyTokens: solUint(constants, "DEFAULT_SUPPLY"),
    devBuyMaxBps: solUint(constants, "DEV_BUY_MAX_BPS"),
    tickerLockSeconds: lockSol,
    tickerLockSecondsTs: lockTs,
    factoryVersion,
    factoryVersionLabel: `V${factoryVersion}`,
    protocolFeePct: bpsToPct(solUint(constants, "PROTOCOL_FEE_BPS")),
    holderFeePct: bpsToPct(solUint(constants, "HOLDER_FEE_BPS")),
    flywheelFeePct: bpsToPct(solUint(constants, "FLYWHEEL_FEE_BPS")),
    coreFeePct: bpsToPct(solUint(constants, "CORE_FEE_BPS")),
    devBuyPct: bpsToPct(solUint(constants, "DEV_BUY_MAX_BPS")),
    tickerLockHours: lockSol / 3600,
  };
}

function dash(v: string | number | null | undefined): string {
  if (v === null || v === undefined || v === "") return "—";
  return String(v);
}

function loadAddresses(rel: string | null): Record<string, string> {
  if (!rel) return {};
  const json = readJson<{ addresses?: Record<string, string> }>(rel);
  return json.addresses ?? {};
}

export function renderVersioning(ver: ProtocolVersion, c: ReturnType<typeof loadCodeConstants>): string {
  return `${GENERATED_BANNER}

# Versioning

> Protocol release **${ver.protocolVersion}** (\`${ver.releaseTag}\`, ${ver.releaseDate}). Factory **${c.factoryVersionLabel}** is immutable and is not this number.

${ver.status}. ${ver.notes}

## Two version numbers

| Kind | What it is | Source of truth | This HEAD |
| --- | --- | --- | --- |
| **Protocol release** | Overall REACTOR software + docs release (semver) | \`docs/version.json\` → \`protocolVersion\` | **${ver.protocolVersion}** |
| **Factory version** | Immutable on-chain factory label for **new launches** | \`ReactorFactory.FACTORY_VERSION\` | **${c.factoryVersionLabel}** (\`${c.factoryVersion}\`) |

Factory **${c.factoryVersionLabel} stays ${c.factoryVersionLabel} forever**. A different fee split, supply, Dev Buy cap, or curve is a **new factory deploy** (V2, V3, …), authorized by Guardian for new launches only. Existing ${c.factoryVersionLabel} tokens are untouched. See \`FACTORY_VERSIONING.md\`.

Bumping \`protocolVersion\` does **not** change Factory ${c.factoryVersionLabel}. Do not retag Factory ${c.factoryVersionLabel} as a protocol version.

## Single source of truth

Edit **\`docs/version.json\`** only. Then run \`pnpm docs:gen\`. CI (\`pnpm docs:check\`) fails if:

- root \`package.json\` \`version\` ≠ \`protocolVersion\`
- \`releaseTag\` ≠ \`v\` + \`protocolVersion\`
- \`CHANGELOG.md\` has no heading for this protocol version
- \`factoryVersion\` / label ≠ Solidity \`FACTORY_VERSION\`
- generated \`docs/versioning.md\` / \`docs/deployments.md\` are stale
- tracked docs / \`BUILD_REPORT.md\` still contain \`<<<<<<<\` / \`>>>>>>>\` conflict markers
- fee / supply / Dev Buy / ticker lock / factory labels in docs drifted from code
- \`deployments/local.json\` copies (web + indexer) drifted
- deployment tables omit a recorded local address, or invent a mainnet (5042) address

## Tagging convention

Every **production** protocol release:

1. Bump \`docs/version.json\` (\`protocolVersion\`, \`releaseTag\`, \`releaseDate\`).
2. Add a \`CHANGELOG.md\` section for that version.
3. Run \`pnpm docs:gen\` and \`pnpm docs:check\`.
4. Commit the docs + version files in the **same** change as the code.
5. Create an annotated git tag matching \`releaseTag\`:

\`\`\`
git tag -a v${ver.protocolVersion} -m "REACTOR protocol ${ver.protocolVersion}"
git push origin v${ver.protocolVersion}
\`\`\`

Rules:

- Tags are \`vMAJOR.MINOR.PATCH\` (leading \`v\`).
- Never move or reuse a tag.
- Factory versions are **not** git tags.
- Pre-audit / local-only baselines still get a changelog + tag so HEAD is identifiable.
- Do not tag Arc Mainnet deploys. There are none.

## Constants frozen in Factory ${c.factoryVersionLabel}

These are code constants. Changing them is a new factory, not a protocol patch.

| Constant | Code | Docs must say |
| --- | --- | --- |
| Protocol fee | \`${c.protocolFeeBps}\` bps | **${c.protocolFeePct}** |
| Holders | \`${c.holderFeeBps}\` bps | **${c.holderFeePct} holders** |
| Top-10 flywheel | \`${c.flywheelFeeBps}\` bps | **${c.flywheelFeePct}** |
| CORE buy+burn | \`${c.coreFeeBps}\` bps | **${c.coreFeePct} CORE** |
| Launch supply | \`${c.defaultSupplyTokens.toLocaleString("en-US")}\` | **${c.defaultSupplyBillions}B** |
| Dev Buy cap | \`${c.devBuyMaxBps}\` bps | **${c.devBuyPct}** token-out |
| Ticker lock | \`${c.tickerLockSeconds}\` s | **${c.tickerLockHours}h** global |

## Related

- [Changelog](/docs/changelog)
- [Deployments](/docs/deployments)
- [Docs policy](/docs/policy)
- \`CONTRIBUTING.md\` · \`FACTORY_VERSIONING.md\` · \`CHANGELOG.md\`
`;
}

function cellAddr(network: RegistryNetwork, addrs: Record<string, string>, key: string | null): string {
  if (network.chainId === 5042) return "— (mainnet blocked; no address)";
  if (!key) return "— (per-launch / not a singleton)";
  if (!network.addressFile) return "— (not deployed / not claimed)";
  const a = addrs[key];
  if (!a) return "— (not in committed address dump)";
  return `\`${a}\``;
}

export function renderDeployments(ver: ProtocolVersion, registry: Registry): string {
  const c = loadCodeConstants();
  const networkRows = registry.networks
    .map((n) => `| ${n.label} | ${n.chainId} | ${n.claimed ? "Claimed" : n.placeholder ? "Placeholder / not claimed" : "Recorded"} | ${n.note} |`)
    .join("\n");

  const sections = registry.networks.map((n) => {
    const addrs = loadAddresses(n.addressFile);
    const source = n.sourceCommit ? `\`${n.sourceCommit}\`` : n.sourceTag ? `\`${n.sourceTag}\`` : "—";
    const date = dash(n.deploymentDate);
    const verify = n.verificationUrl ? `[verify](${n.verificationUrl})` : n.verificationNote;
    const rows = registry.contracts
      .map((ct) => {
        const fv = ct.factoryVersion === null ? "—" : `V${ct.factoryVersion}`;
        return `| ${ct.name} | ${fv} | ${ver.protocolVersion} | ${cellAddr(n, addrs, ct.addressKey)} | ${n.chain} (${n.chainId}) | ${source} | ${date} | ${verify} |`;
      })
      .join("\n");
    return `## ${n.label}

${n.note}

| Contract | Factory version | Protocol release | Address | Chain | Source commit/tag | Deployment date | Verification |
| --- | --- | --- | --- | --- | --- | --- | --- |
${rows}
`;
  });

  return `${GENERATED_BANNER}

# Deployments

> Generated from \`deployments/registry.json\` + address dumps. Protocol **${ver.protocolVersion}**. Factory **${c.factoryVersionLabel}**. Never invent mainnet addresses.

| Network | Chain ID | Status | Notes |
| --- | --- | --- | --- |
${networkRows}

v4 \`PoolManager\`: production accepts **verified** Arc addresses only. This repo does not hardcode a mainnet or unverified testnet PoolManager.

SAFE genesis: Batch A (config while paused, including Launch Signer + TickerRegistry + authorizeFactory) → Verify → Batch B (vesting T0 + \`pauseLaunches(false)\`).

${sections.join("\n")}
## How to record a real deploy

1. Deploy with \`forge script script/Deploy.s.sol:Deploy\` (writes \`deployments/local.json\` and app copies).
2. For a **claimed** testnet: add a dedicated address file (never overwrite the local placeholder without labeling), set \`sourceCommit\` to the exact git SHA, \`sourceTag\` to \`docs/version.json\` \`releaseTag\`, \`deploymentDate\`, and a real explorer \`verificationUrl\`.
3. Run \`pnpm docs:gen\`. Commit registry + generated \`docs/deployments.md\` together.
4. Mainnet (5042): do not add addresses. Keep the blocked row.
`;
}

export function renderChangelogDoc(changelog: string, ver: ProtocolVersion): string {
  const body = changelog.replace(/^# Changelog\s*/m, "").trim();
  return `${GENERATED_BANNER}

# Changelog

Protocol release **${ver.protocolVersion}** (\`${ver.releaseTag}\`). Factory **${ver.factoryVersionLabel}** is unchanged by this number.

The canonical file is \`CHANGELOG.md\` at the repo root. Same content below.

${body}
`;
}

export function generate(): { versioning: string; deployments: string; changelog: string } {
  const ver = loadVersion();
  const c = loadCodeConstants();
  const registry = readJson<Registry>("deployments/registry.json");
  return {
    versioning: renderVersioning(ver, c),
    deployments: renderDeployments(ver, registry),
    changelog: renderChangelogDoc(read("CHANGELOG.md"), ver),
  };
}

export function writeGenerated(): void {
  const g = generate();
  writeFileSync(join(root, "docs/versioning.md"), g.versioning);
  writeFileSync(join(root, "docs/deployments.md"), g.deployments);
  writeFileSync(join(root, "docs/changelog.md"), g.changelog);
}

function mustMatch(rel: string, expected: string, errors: string[]) {
  const actual = existsSync(join(root, rel)) ? read(rel) : "";
  if (actual !== expected) errors.push(`${rel} is stale — run pnpm docs:gen`);
}

function collectDocCorpus(): string {
  const files = [
    "docs/index.md",
    "docs/fees.md",
    "docs/tickers.md",
    "docs/creators.md",
    "docs/core.md",
    "docs/versioning.md",
    "docs/deployments.md",
    "docs/policy.md",
    "docs/changelog.md",
    "README.md",
    "ECONOMICS.md",
    "FACTORY_VERSIONING.md",
    "CHANGELOG.md",
    "CONTRIBUTING.md",
  ];
  return files.filter((f) => existsSync(join(root, f))).map(read).join("\n");
}

export function check(): string[] {
  const errors: string[] = [];
  const ver = loadVersion();
  const c = loadCodeConstants();
  const rootPkg = readJson<{ version?: string }>("package.json");
  const registry = readJson<Registry>("deployments/registry.json");

  if (!/^\d+\.\d+\.\d+$/.test(ver.protocolVersion)) {
    errors.push(`protocolVersion must be semver MAJOR.MINOR.PATCH, got ${ver.protocolVersion}`);
  }
  if (ver.releaseTag !== `v${ver.protocolVersion}`) {
    errors.push(`releaseTag ${ver.releaseTag} must be v${ver.protocolVersion}`);
  }
  if (rootPkg.version !== ver.protocolVersion) {
    errors.push(`package.json version ${rootPkg.version} != protocolVersion ${ver.protocolVersion}`);
  }
  if (ver.factoryVersion !== c.factoryVersion) {
    errors.push(`version.json factoryVersion ${ver.factoryVersion} != Solidity FACTORY_VERSION ${c.factoryVersion}`);
  }
  if (ver.factoryVersionLabel !== c.factoryVersionLabel) {
    errors.push(`factoryVersionLabel ${ver.factoryVersionLabel} != ${c.factoryVersionLabel}`);
  }
  if (c.tickerLockSeconds !== c.tickerLockSecondsTs) {
    errors.push(`Ticker.sol LOCK_SECONDS ${c.tickerLockSeconds} != ticker.ts ${c.tickerLockSecondsTs}`);
  }

  const changelog = read("CHANGELOG.md");
  const heading = new RegExp(`^## \\[${ver.protocolVersion.replace(/\./g, "\\.")}\\]`, "m");
  if (!heading.test(changelog)) {
    errors.push(`CHANGELOG.md missing ## [${ver.protocolVersion}] heading`);
  }

  const g = generate();
  mustMatch("docs/versioning.md", g.versioning, errors);
  mustMatch("docs/deployments.md", g.deployments, errors);
  mustMatch("docs/changelog.md", g.changelog, errors);

  const docs = collectDocCorpus();
  const expectMentions: [RegExp, string][] = [
    [new RegExp(ver.protocolVersion.replace(/\./g, "\\.")), `protocol ${ver.protocolVersion}`],
    [new RegExp(c.protocolFeePct.replace(".", "\\.")), `fee ${c.protocolFeePct}`],
    [/2% holders/, "2% holders"],
    [new RegExp(`${c.defaultSupplyBillions}B`), `${c.defaultSupplyBillions}B supply`],
    [new RegExp(`${c.devBuyPct}`), `Dev Buy ${c.devBuyPct}`],
    [new RegExp(`${c.tickerLockHours}h`), `${c.tickerLockHours}h ticker lock`],
    [new RegExp(`FACTORY_VERSION = ${c.factoryVersion}|Factory \\*\\*${c.factoryVersionLabel}`), `factory ${c.factoryVersionLabel}`],
  ];
  for (const [re, label] of expectMentions) {
    if (!re.test(docs)) errors.push(`docs corpus missing ${label}`);
  }
  if (/audited and trustless/i.test(docs)) errors.push("docs claim audited and trustless");

  const local = read("deployments/local.json");
  for (const copy of ["apps/web/src/lib/deployment.json", "apps/indexer/src/deployment.json"]) {
    if (read(copy) !== local) errors.push(`${copy} drifted from deployments/local.json`);
  }

  const localAddrs = loadAddresses("deployments/local.json");
  const generatedDep = g.deployments;
  for (const [key, addr] of Object.entries(localAddrs)) {
    const listed = registry.contracts.some((ct) => ct.addressKey === key);
    if (!listed) {
      // Roles / mocks that are not protocol contracts may exist; still require the address appear if keyed.
      if (["USDC", "ZEC", "BTC", "NVDA"].includes(key)) continue;
      if (!generatedDep.includes(addr)) errors.push(`deployment table missing local address for ${key}`);
    } else if (!generatedDep.includes(addr)) {
      errors.push(`generated deployments.md missing ${key} ${addr}`);
    }
  }

  const mainnet = registry.networks.find((n) => n.chainId === 5042);
  if (!mainnet) errors.push("registry missing chain 5042 blocked row");
  else {
    if (mainnet.addressFile) errors.push("mainnet registry must not point at an address file");
    if (mainnet.claimed) errors.push("mainnet must not be marked claimed");
  }
  const mainnetSection = generatedDep.split("## Arc Mainnet")[1] ?? "";
  if (/0x[a-fA-F0-9]{40}/.test(mainnetSection)) {
    errors.push("generated mainnet section contains a contract address — do not invent mainnet addresses");
  }

  if (!existsSync(join(root, "CONTRIBUTING.md"))) errors.push("CONTRIBUTING.md missing");
  if (!existsSync(join(root, "docs/policy.md"))) errors.push("docs/policy.md missing");

  for (const rel of conflictMarkerFiles()) {
    const text = read(rel);
    if (/^<<<<<<< /m.test(text) || /^>>>>>>> /m.test(text)) {
      errors.push(`${rel} contains unresolved conflict markers`);
    }
  }

  return errors;
}

function conflictMarkerFiles(): string[] {
  const files = [
    "BUILD_REPORT.md",
    "AUDIT_HANDOFF.md",
    "TESTING.md",
    "CHANGELOG.md",
    "README.md",
    "ARCHITECTURE.md",
    "CONTRIBUTING.md",
    "ECONOMICS.md",
    "FACTORY_VERSIONING.md",
    "UX_REFERENCE.md",
  ];
  const docsDir = join(root, "docs");
  if (existsSync(docsDir)) {
    for (const name of readdirSync(docsDir)) {
      if (name.endsWith(".md")) files.push(`docs/${name}`);
    }
  }
  return files.filter((f) => existsSync(join(root, f)));
}

const cmd = process.argv[2] ?? "check";
if (import.meta.url === `file://${process.argv[1]}` || process.argv[1]?.endsWith("sync-docs.ts")) {
  if (cmd === "generate" || cmd === "gen") {
    writeGenerated();
    console.log("docs generated: versioning.md deployments.md changelog.md");
  } else if (cmd === "check") {
    const errors = check();
    if (errors.length) {
      console.error("docs/constants sync FAILED:");
      for (const e of errors) console.error(` - ${e}`);
      process.exit(1);
    }
    console.log("docs/constants/version/deployments sync ok");
  } else {
    console.error("usage: tsx scripts/sync-docs.ts generate|check");
    process.exit(2);
  }
}
