export type DocNav = {
  slug: string;
  title: string;
  group: string;
  file: string;
  blurb: string;
  keywords: string;
};

/** In-app handbook. Order is the GitBook-style reading order and prev/next. */
export const DOCS: DocNav[] = [
  {
    slug: "",
    title: "How REACTOR works",
    group: "Start",
    file: "index.md",
    blurb: "Handbook home: bonding curve to locked v4, 3.5% quote split, frozen knobs, trust.",
    keywords: "introduction overview launchpad instant fair factory v1 2% holders not audited",
  },
  {
    slug: "local",
    title: "Local demo",
    group: "Start",
    file: "local.md",
    blurb: "Run Anvil 5042002, deploy Factory V1, indexer, signer, and the web app locally.",
    keywords: "quickstart anvil foundry pnpm 43147 43148 43149 deploy local.json",
  },
  {
    slug: "traders",
    title: "Traders",
    group: "Audience",
    file: "traders.md",
    blurb: "Exact-in trades, quote tickets, two SELL floors, rewards, board and tape.",
    keywords: "trade buy sell minOut minQuoteOut feeLegs slippage rewards claim board",
  },
  {
    slug: "creators",
    title: "Creators",
    group: "Audience",
    file: "creators.md",
    blurb: "Launch Instant or Fair. You pick identity and quote. Protocol owns supply, curve, fees.",
    keywords: "launch ignite ticker image quote rewards standard dev buy 5% 1B turnstile",
  },
  {
    slug: "builders",
    title: "Builders",
    group: "Audience",
    file: "builders.md",
    blurb: "Integrate as a client: markets, quote tickets, authorize, media, SSE.",
    keywords: "terminal sdk api indexer integrate partner hop kinds proven venues",
  },
  {
    slug: "qa",
    title: "UI QA gate",
    group: "Builders",
    file: "qa.md",
    blurb: "Visual, a11y, and failure-injection Playwright gate versus production next build.",
    keywords: "qa visual a11y inject failure console contrast playwright",
  },
  {
    slug: "economics",
    title: "Economics",
    group: "Protocol",
    file: "economics.md",
    blurb: "0% LP fee, 3.5% quote-side split, no creator fee, Instant vs Fair inventory.",
    keywords: "tokenomics 350 bps 200 100 50 selfburn flywheel core 6.88% 688",
  },
  {
    slug: "lifecycle",
    title: "Launch lifecycle",
    group: "Protocol",
    file: "lifecycle.md",
    blurb: "Instant bonding → ready → frozen → graduate. Fair pro-rata sale then 50/50 lock.",
    keywords: "ready locked graduate InstantCurve fair auction 0% sale 79.31 20.69",
  },
  {
    slug: "curve",
    title: "Curve math",
    group: "Protocol",
    file: "curve.md",
    blurb: "Frozen virtual-reserve Instant curve. ~$5k start FDV. Dev Buy cap 5%.",
    keywords: "virtualQuote0 INSTANT_CURVE_V1 793100000 206900000 15200 73469",
  },
  {
    slug: "fees",
    title: "Nested fees",
    group: "Protocol",
    file: "fees.md",
    blurb: "Each official hop charges 3.5% of that hop's quote. feeLegs[] on the scored winner.",
    keywords: "feeLegs aggregateProtocolImpactBps exemptOfficialLegs hookless compound",
  },
  {
    slug: "rewards",
    title: "Rewards",
    group: "Protocol",
    file: "rewards.md",
    blurb: "O(1) same-quote holder rewards. eligibleSupply==0 sends 2% to SelfBurn.",
    keywords: "dividend claim standard selfburn no staking persist transfer magnified",
  },
  {
    slug: "top-10",
    title: "Top-10",
    group: "Protocol",
    file: "top-10.md",
    blurb: "1% flywheel. Ranks are an offchain API. Contracts check structure only.",
    keywords: "reactor flywheel epoch 250k floor weights CORE excluded trusted computation GET /top10 v11",
  },
  {
    slug: "core",
    title: "CORE",
    group: "Protocol",
    file: "core.md",
    blurb: "Genesis 100M vest + 900M locked CORE/USDC. Never Instant. Never Top-10.",
    keywords: "10/90 2.5% burn vesting cliff CoreToken TestCORE 100k fdv single-sided",
  },
  {
    slug: "routes",
    title: "Routes",
    group: "Protocol",
    file: "routes.md",
    blurb: "Proven venues only. Max 3 hops. One eth_call per candidate. pickBest winner.",
    keywords: "OFFICIAL_REACTOR_V4 EXTERNAL_V4_HOOKLESS BONDING_CURVE UserRouteQuoter",
  },
  {
    slug: "quoting",
    title: "Atomic quoter",
    group: "Protocol",
    file: "quoting.md",
    blurb: "UserRouteQuoter PreviewRoute. plannedHops+1. Two SELL floors from one preview.",
    keywords: "previewBuy previewSell hopOuts minQuoteOut minFinalOut applySlippage",
  },
  {
    slug: "valuation",
    title: "Valuation",
    group: "Protocol",
    file: "valuation.md",
    blurb: "Single USD engine. usdPegOne only for $1. Multi-source consensus. Fail closed.",
    keywords: "ValuationService consensusUsd6 current_supply fdv_usd6 EURC price-providers",
  },
  {
    slug: "architecture",
    title: "Architecture",
    group: "Protocol",
    file: "architecture.md",
    blurb: "Immutable modules, official pool identity, swap path, offchain trust boundaries.",
    keywords: "ReactorHook Factory InstantLaunchModule vaults PoolManager indexer signer",
  },
  {
    slug: "trust",
    title: "Trust assumptions",
    group: "Protocol",
    file: "trust.md",
    blurb: "What is trusted, what is onchain, what fail-closes. Not an oracle. Not audited.",
    keywords: "top-10 signer indexer guardian keeper turnstile r2 json cap 5042",
  },
  {
    slug: "security",
    title: "Security model",
    group: "Protocol",
    file: "security.md",
    blurb: "Guardian brake pedal, Keeper blast radius, residual risks, privilege map.",
    keywords: "threat model privilege pause quarantine protocolExempt no withdraw no mint",
  },
  {
    slug: "web-security",
    title: "Browser security",
    group: "Protocol",
    file: "web-security.md",
    blurb: "Untrusted token metadata, CSP nonce, tx-guard, chain-mismatch hard block.",
    keywords: "csp nonce unsafe-inline sanitize tx-guard xss metadata untrusted NEXT_PUBLIC",
  },
  {
    slug: "geo-policy",
    title: "Geo policy",
    group: "Protocol",
    file: "geo-policy.md",
    blurb: "Server ALLOW / DENY / UNKNOWN over verified edge HMAC. Not a UI country list.",
    keywords: "HMAC edge geo ALLOW DENY UNKNOWN oblast FAQ 1009 #63 #67",
  },
  {
    slug: "restricted-access",
    title: "Restricted access",
    group: "Protocol",
    file: "restricted-access.md",
    blurb: "Hosted /restricted UX when operated writes are deny or unavailable. Not an onchain pause.",
    keywords: "restricted /restricted deny unavailable CTA banner account location #65 #75",
  },
  {
    slug: "sanctions-ops",
    title: "Sanctions ops",
    group: "Protocol",
    file: "sanctions-ops.md",
    blurb: "Official-list freshness SLA, last-known-good refresh, health, and minimized audit.",
    keywords: "7-day SLA last-known-good retrievedAt alerts runbook #64 #70",
  },
  {
    slug: "sanctions-runbook",
    title: "Sanctions runbook",
    group: "Protocol",
    file: "sanctions-runbook.md",
    blurb: "Operator steps for stale, missing, or degraded official-list freshness.",
    keywords: "runbook refresh stale missing last-known-good incident #64",
  },
  {
    slug: "incident-response",
    title: "Incident response",
    group: "Protocol",
    file: "incident-response.md",
    blurb: "Operator incident path. Links the sanctions runbook. Not a protocol pause.",
    keywords: "incident runbook sanctions-ops freshness Guardian Keeper #79",
  },
  {
    slug: "tickers",
    title: "Ticker registry",
    group: "Launch",
    file: "tickers.md",
    blurb: "Global 24h lock, reserved names, permanent Guardian lock, EIP-712 verifyingContract.",
    keywords: "TickerRegistry normalize 1-10 CORE USDC claimOnLaunch permanentlyLockTicker",
  },
  {
    slug: "admission",
    title: "Launch admission",
    group: "Launch",
    file: "admission.md",
    blurb: "Turnstile, ALLOW/CHALLENGE/DENY, isolated signer, issuance bucket, fail-closed store.",
    keywords: "launchConfigHash receipt SIGNER_STORE_UNAVAILABLE 16KiB 64KiB funding-cluster",
  },
  {
    slug: "sanctions",
    title: "Address screening",
    group: "Launch",
    file: "sanctions.md",
    blurb: "Exact official-list OFAC/Treasury address lookup. Not compliance. Not hop attribution.",
    keywords: "OFAC SDN screen blocked clear unavailable last-known-good #61 #66",
  },
  {
    slug: "operator-policy",
    title: "Operator policy",
    group: "Launch",
    file: "operator-policy.md",
    blurb: "Server-side write/authorization gate: recovered wallet proof + trusted geo + freshness.",
    keywords: "evaluateOperatorPolicy gateProtectedWrite wallet-proof #62 #68",
  },
  {
    slug: "guardian",
    title: "Guardian",
    group: "Launch",
    file: "guardian.md",
    blurb: "Only privileged security authority. Immutable Safe. Cannot steal LP or rewrite 2/1/0.5.",
    keywords: "pause setKeeper setUsdPegOne authorizeFactory Safe genesis Batch A B",
  },
  {
    slug: "keeper",
    title: "Keeper",
    group: "Launch",
    file: "keeper.md",
    blurb: "Designated maintenance. One lease, 20% chunks, fee-exempt planner, no bounty.",
    keywords: "leader_locks renew fence DRY_RUN LOCAL ARC_TESTNET watchdog 5042 disabled",
  },
  {
    slug: "automation",
    title: "Automation",
    group: "Launch",
    file: "automation.md",
    blurb: "AutomationGateway is keeper. Relayers deliver signed MaintenanceJobs. CRE does not rank.",
    keywords: "AutomationGateway MaintenanceJob jobSigner relayer CRE Gelato valuationSnapshotHash",
  },
  {
    slug: "api",
    title: "API",
    group: "Builders",
    file: "api.md",
    blurb: "Public indexer HTTP. Quote, markets, launch authorize, upload, stream, health.",
    keywords: "POST /quote GET /markets /launch/authorize /pricing/health 413 request_id",
  },
  {
    slug: "sdk",
    title: "SDK",
    group: "Builders",
    file: "sdk.md",
    blurb: "@reactor/sdk client and @reactor/core helpers. No isolated-signer access.",
    keywords: "ReactorClient baseUrl authorize markets admit stream planCandidates",
  },
  {
    slug: "examples",
    title: "Examples",
    group: "Builders",
    file: "examples.md",
    blurb: "curl tickets for quote, authorize, markets keyset, candles, valuation.",
    keywords: "curl BUY SELL CHALLENGE next_cursor 688 aggregateProtocolImpactBps",
  },
  {
    slug: "events",
    title: "Events",
    group: "Builders",
    file: "events.md",
    blurb: "Ingest journal identity, atomic persist, burns vs attribution, SSE after commit.",
    keywords: "persistTickBatch indexer_event_journal current_supply schema v8 v9 v10",
  },
  {
    slug: "markets",
    title: "Markets API",
    group: "Builders",
    file: "markets.md",
    blurb: "Board keyset, burn-adjusted FDV, candles, tape, 24h rolls.",
    keywords: "cursor_ts cursor_token volume_24h_usd6 fdv_usd6 gap-fill before_id",
  },
  {
    slug: "perf",
    title: "Read path performance",
    group: "Builders",
    file: "perf.md",
    blurb: "Indexed HTTP first, batched RPC fallback, page-budget CI. Live POST /quote stays fail-closed.",
    keywords: "page-budget Multicall3 TanStack indexed /page/token quote-assets abort SSE #37 #50",
  },
  {
    slug: "media",
    title: "Media",
    group: "Builders",
    file: "media.md",
    blurb: "2MB stream, sharp WebP, SigV4, object key m/<id>.webp matches public URL.",
    keywords: "upload R2 S3 MEDIA_CDN_BASE sharp approve-builds no base64",
  },
  {
    slug: "observability",
    title: "Observability",
    group: "Builders",
    file: "observability.md",
    blurb: "Redacted failure telemetry, Sentry-or-equivalent, error boundaries, release SHA.",
    keywords: "sentry telemetry source maps redact error boundary /api/version /api/telemetry",
  },
  {
    slug: "deployments",
    title: "Deployments",
    group: "Builders",
    file: "deployments.md",
    blurb: "Generated address tables. No invented mainnet. Local Anvil only unless claimed.",
    keywords: "registry.json local.json 5042 blocked Safe genesis claimed",
  },
  {
    slug: "arc",
    title: "Arc",
    group: "Reference",
    file: "arc.md",
    blurb: "Chain 5042002, gas USDC-18 vs protocol USDC-6, BFT finality, no mainnet.",
    keywords: "5042 5042002 arcscan PoolManager BUSL deterministic finality",
  },
  {
    slug: "faq",
    title: "FAQ",
    group: "Reference",
    file: "faq.md",
    blurb: "Audit, mainnet, Turnstile, EURC, two mins, Factory vs protocol version.",
    keywords: "wrongparams challenge minOut confirmations safe json factory v1",
  },
  {
    slug: "glossary",
    title: "Glossary",
    group: "Reference",
    file: "glossary.md",
    blurb: "Official pool, Instant, Fair, usdPegOne, quoter, Guardian, Keeper, CORE.",
    keywords: "definitions terms INSTANT_CURVE_V1 FAIR_V1 launchConfigHash",
  },
  {
    slug: "troubleshooting",
    title: "Troubleshooting",
    group: "Reference",
    file: "troubleshooting.md",
    blurb: "Unavailable routes, 413, 503 signer store, CHALLENGE loops, ticker lock.",
    keywords: "ok false dust SIGNER_STORE_UNAVAILABLE TickerUnavailable ReadyLocked",
  },
  {
    slug: "versioning",
    title: "Versioning",
    group: "Reference",
    file: "versioning.md",
    blurb: "Protocol semver in version.json. Factory V1 stays V1 forever.",
    keywords: "protocolVersion FACTORY_VERSION docs:gen docs:check changelog tag",
  },
  {
    slug: "changelog",
    title: "Changelog",
    group: "Reference",
    file: "changelog.md",
    blurb: "Production protocol releases. Factory label is a different number.",
    keywords: "keep a changelog protocol release unreleased tokenomics unchanged",
  },
  {
    slug: "policy",
    title: "Docs policy",
    group: "Reference",
    file: "policy.md",
    blurb: "Docs ship in the same run as behavior. CI fails on economic drift.",
    keywords: "CONTRIBUTING mandatory same commit generated pages",
  },
  {
    slug: "brand",
    title: "Brand",
    group: "Reference",
    file: "brand.md",
    blurb: "Industrial Forge is the locked product identity. Economics and Factory V1 are unchanged.",
    keywords: "industrial forge brand slag steel heat paper direction C specimen",
  },
  {
    slug: "ci",
    title: "CI and cost",
    group: "Reference",
    file: "ci.md",
    blurb: "Three-tier GitHub Actions. Fast PR units, full merge-candidate, one main post-merge path.",
    keywords: "ci-cost three-tier fast full main workflow_dispatch ci-full docs:check #69",
  },
  {
    slug: "publicization",
    title: "Repo publicization",
    group: "Reference",
    file: "publicization.md",
    blurb: "Operator checklist to maybe make the GitHub repo public. Not mainnet readiness.",
    keywords: "public fork actions persist-credentials gitleaks founder visibility #72",
  },
];

export function slugify(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

export function docHref(slug: string): string {
  return slug ? `/docs/${slug}` : "/docs";
}

export function adjacentDocs(slug: string): { prev?: DocNav; next?: DocNav } {
  const i = DOCS.findIndex((d) => d.slug === slug);
  if (i < 0) return {};
  return { prev: DOCS[i - 1], next: DOCS[i + 1] };
}
